var config = {
	comment: "See https://github.com/thomasjacquin/allsky/wiki/allsky-website-Settings for a description of these settings",
	title: "Astrofield",
	imageName: "/media/image.jpg",
	location: "Lithuania",
	latitude_longitude_comment: "latitude and longitude must be decimal numbers with OUT the trailing N, S, E, and W.",
	latitude: 55.69384801953093,
	longitude: 22.872974280818735,
	az: 0,
	camera: "Raspberry Pi V2 camera",
	lens: "ArduCam B0180",
	computer: "Raspberry Pi 3 Model B+",
	owner: "minjja",
	overlaySize: 875,
	overlayOffsetLeft: 0,
	overlayOffsetTop: 0,
	showOverlayAtStartup: false,
	auroraForecast: false,
	auroraMap: "XX_need_to_update_XX",
	intervalSeconds: 5,
}