var config = {
	comment: "See https://github.com/thomasjacquin/allsky/wiki/allsky-website-Settings for a description of these settings",
	title: "Astrofield",
	imageName: "/current/tmp/image.jpg",
	location: "Lithuania, Miežaičiai",
	latitude_longitude_comment: "latitude and longitude must be decimal numbers with OUT the trailing N, S, E, and W.",
	latitude: 0,
	longitude: 0,
	az: 0,
	camera: "XX_need_to_update_XX",
	lens: "XX_need_to_update_XX",
	computer: "Raspberry Pi 3 Model B+",
	owner: "minjja",
	overlaySize: 875,
	overlayOffsetLeft: 0,
	overlayOffsetTop: 0,
	showOverlayAtStartup: false,
	auroraForecast: false,
	auroraMap: "XX_need_to_update_XX",
	intervalSeconds: 5,
}