version: '3.7'

services:

    nginx:
        image: nginx
        ports:
            - 80:80/tcp
            - 443:443/tcp
        configs:
            - source: nginx.conf
              target: /etc/nginx/conf.d/default.conf
        secrets:
            - source: ssl_certificate
              target: /etc/letsencrypt/cert.crt
            - source: ssl_certificate_key
              target: /etc/letsencrypt/private.key

    webdav:
        image: ghcr.io/minjja/webdav
        secrets:
            - source: htpasswd
              target: /usr/local/apache2/.htpasswd
            - source: ssl_certificate_key
              target: /usr/local/apache2/ssl/key.pem
            - source: ssl_certificate
              target: /usr/local/apache2/ssl/cert.pem
        volumes:
            - type: volume
              source: uploads
              target: /usr/local/apache2/uploads/

    website:
        image: ghcr.io/minjja/allsky-website
        configs:
            - source: config.js
              target: /var/www/html/config.js
            - source: virtualsky.json
              target: /var/www/html/virtualsky.json
        environment:
            ALLSKY_VIDEOS: ../../webdav/videos
            ALLSKY_KEOGRAMS: ../../webdav/keograms
            ALLSKY_STARTRAILS: ../../webdav/startrails
        volumes:
            - type: volume
              source: webdav
              target: /var/www/webdav

volumes:
    uploads:

configs:
    nginx.conf:
        file: ./etc/nginx.conf
    config.js:
        file: ./src/config.js
    virtualsky.json:
        file: ./src/virtualsky.json

secrets:
    htpasswd:
        external: true
    ssl_certificate:
        file: ./etc/letsencrypt/live/allsky/cert.pem
    ssl_certificate_key:
        file: ./etc/letsencrypt/live/allsky/privkey.pem
