version: '3.7'

services:

    nginx:
        image: nginx
        ports:
            - 80:80/tcp
        configs:
            - source: nginx.conf
              target: /etc/nginx/conf.d/default.conf
        secrets:
            - source: ssl_certificate
              target: /etc/ssl/cert.pem
            - source: ssl_certificate_key
              target: /etc/ssl/key.pem
        volumes:
            - type: volume
              source: html
              target: /usr/share/nginx/html

    webdav:
        image: ghcr.io/minjja/webdav
        ports:
            - 8443:443/tcp
        configs:
            - source: webdav.conf
              target: /usr/local/apache2/conf/user.conf
        secrets:
            - source: htpasswd
              target: /usr/local/apache2/.htpasswd
            - source: ssl_certificate
              target: /usr/local/apache2/ssl/cert.pem
            - source: ssl_certificate_key
              target: /usr/local/apache2/ssl/key.pem
        volumes:
            - type: volume
              source: uploads
              target: /usr/local/apache2/uploads

    website:
        image: ghcr.io/minjja/allsky-website
        ports:
            - 443:443/tcp
        secrets:
            - source: ssl_certificate
              target: /etc/apache2/ssl/cert.pem
            - source: ssl_certificate_key
              target: /etc/apache2/ssl/key.pem
        configs:
            - source: website.conf
              target: /etc/apache2/sites-enabled/default-ssl.conf
            - source: config.js
              target: /var/www/html/config.js
            - source: virtualsky.json
              target: /var/www/html/virtualsky.json
        environment:
            ALLSKY_VIDEOS: ../uploads/allsky/videos
            ALLSKY_KEOGRAMS: ../uploads/allsky/keograms
            ALLSKY_STARTRAILS: ../uploads/allsky/startrails
        volumes:
            - type: volume
              source: uploads
              target: /var/www/html/uploads

    mosquitto:
        image: eclipse-mosquitto
        ports:
            - 1883:1883/tcp
            - 9001:9001/tcp
        configs:
            - source: mosquitto.conf
              target: /mosquitto/config/mosquitto.conf

volumes:
    html:
    uploads:

configs:
    mosquitto.conf:
        file: ./etc/mosquitto.conf
    website.conf:
        file: ./etc/website.conf
    webdav.conf:
        file: ./etc/webdav.conf
    nginx.conf:
        file: ./etc/nginx.conf
    config.js:
        file: ./src/config.js
    virtualsky.json:
        file: ./src/virtualsky.json

secrets:
    htpasswd:
        external: true
    ssl_certificate:
        file: ./ssl/live/allsky/cert.pem
    ssl_certificate_key:
        file: ./ssl/live/allsky/privkey.pem
