version: '3.7'

services:

    httpd:
        image: httpd
        ports:
            - 80:80/tcp
        volumes:
            - type: bind
              source: ./html
              target: /var/www/html

    certbot:
        image: certbot/certbot
        volumes:
            - type: bind
              source: ./html
              target: /public
            - type: bind
              source: ./etc/letsencrypt/
              target: /etc/letsencrypt
        command: |
            certonly
            --agree-tos
            --cert-name allsky
            --webroot --webroot-path=/public
            --register-unsafely-without-email
            --domains allsky1.cloud.cherryservers.net
        depends_on:
            - httpd
