version: '3.7'

services:

    app:
        image: ghcr.io/minjja/allsky-website
        ports:
            - 443:443/tcp
        secrets:
            - source: htpasswd
              target: /etc/apache2/.htpasswd
        configs:
            - source: php.ini
              target: /usr/local/etc/php/php.ini
            - source: config.js
              target: /var/www/html/config.js
            - source: virtualsky.json
              target: /var/www/html/virtualsky.json
        volumes:
            - type: volume
              source: webdav
              target: /var/www/webdav
        environment:
            ALLSKY_VIDEOS: ../../webdav/videos
            ALLSKY_KEOGRAMS: ../../webdav/keograms
            ALLSKY_STARTRAILS: ../../webdav/startrails

volumes:
    webdav:

configs:
    privkey.pem:
        file: ./etc/letsencrypt/live/allsky.cloud.cherryservers.net/privkey.pem
    fullchain.pem:
        file: ./etc/letsencrypt/live/allsky.cloud.cherryservers.net/fullchain.pem
    php.ini:
        file: ./etc/php.ini
    config.js:
        file: ./src/config.js
    virtualsky.json:
        file: ./src/virtualsky.json

secrets:
    htpasswd:
        external: true
