version: '3.7'

services:

    nginx:
        image: nginx
        ports:
            - 80:80/tcp
            - 443:443/tcp
        configs:
            - source: nginx.conf
              target: /etc/nginx/conf.d/default.conf
        secrets:
            - source: ssl_certificate
              target: /etc/ssl/cert.pem
            - source: ssl_certificate_key
              target: /etc/ssl/key.pem
        volumes:
            - type: volume
              source: html
              target: /usr/share/nginx/html

    webdav:
        image: ghcr.io/minjja/webdav
        ports:
            - 8443:8443/tcp
        configs:
            - source: user.conf
              target: /usr/local/apache2/conf/user.conf
        secrets:
            - source: htpasswd
              target: /usr/local/apache2/.htpasswd
            - source: ssl_certificate
              target: /usr/local/apache2/ssl/cert.pem
            - source: ssl_certificate_key
              target: /usr/local/apache2/ssl/key.pem
        volumes:
            - type: volume
              source: uploads
              target: /usr/local/apache2/uploads

    website:
        image: ghcr.io/minjja/allsky-website
        configs:
            - source: config.js
              target: /var/www/html/config.js
            - source: virtualsky.json
              target: /var/www/html/virtualsky.json
        environment:
            ALLSKY_VIDEOS: ../media/videos
            ALLSKY_KEOGRAMS: ../media/keograms
            ALLSKY_STARTRAILS: ../media/startrails
        volumes:
            - type: volume
              source: uploads
              target: /var/www/html/media

volumes:
    html:
    uploads:

configs:
    user.conf:
        file: ./etc/user.conf
    nginx.conf:
        file: ./etc/nginx.conf
    config.js:
        file: ./src/config.js
    virtualsky.json:
        file: ./src/virtualsky.json

secrets:
    htpasswd:
        external: true
    ssl_certificate:
        file: ./ssl/live/allsky/cert.pem
    ssl_certificate_key:
        file: ./ssl/live/allsky/privkey.pem
