version: '3.7'

services:

    app:
        image: ghcr.io/minjja/allsky-website
        ports:
            - 80:80/tcp
            - 443:443/tcp
        secrets:
            - source: htpasswd
              target: /etc/apache2/.htpasswd
        configs:
            - source: config.js
              target: /var/www/html/config.js
            - source: virtualsky.json
              target: /var/www/html/virtualsky.json
        volumes:
            - type: volume
              source: webdav
              target: /var/www/webdav
        environment:
            ALLSKY_VIDEOS: ../../webdav/videos
            ALLSKY_KEOGRAMS: ../../webdav/keograms
            ALLSKY_STARTRAILS: ../../webdav/startrails

volumes:
    webdav:

configs:
    config.js:
        external: true
    virtualsky.json:
        external: true

secrets:
    htpasswd:
        external: true
