version: '3.7'

services:

    nginx:
        image: nginx:1.23
        ports:
            - 443:443/tcp
        configs:
            - source: nginx.conf
              target: /etc/nginx/conf.d/default.conf
        secrets:
            - source: ssl_certificate
              target: /etc/letsencrypt/cert.crt
            - source: ssl_certificate_key
              target: /etc/letsencrypt/private.key

    app:
        image: ghcr.io/minjja/allsky-website
        secrets:
            - source: htpasswd
              target: /etc/apache2/.htpasswd
        configs:
            - source: php.ini
              target: /usr/local/etc/php/php.ini
            - source: config.js
              target: /var/www/html/config.js
            - source: virtualsky.json
              target: /var/www/html/virtualsky.json
        volumes:
            - type: volume
              source: webdav
              target: /var/www/webdav
        environment:
            ALLSKY_VIDEOS: ../../webdav/videos
            ALLSKY_KEOGRAMS: ../../webdav/keograms
            ALLSKY_STARTRAILS: ../../webdav/startrails

volumes:
    webdav:

configs:
    php.ini:
        file: ./etc/php.ini
    nginx.conf:
        file: ./etc/nginx.conf
    config.js:
        file: ./src/config.js
    virtualsky.json:
        file: ./src/virtualsky.json

secrets:
    htpasswd:
        external: true
    ssl_certificate:
        file: ./etc/letsencrypt/live/allsky2.cloud.cherryservers.net/cert.pem
    ssl_certificate_key:
        file: ./etc/letsencrypt/live/allsky2.cloud.cherryservers.net/privkey.pem
