version: '3.7'

services:

    app:
        image: ghcr.io/minjja/allsky-website
        ports:
            - 80:80/tcp
        configs:
            - source: config.js
              target: /var/www/html/config.js
        volumes:
            - type: volume
              source: media
              target: /var/www/html/media
        environment:
            ALLSKY_VIDEOS: /var/www/html/media/videos
            ALLSKY_KEOGRAMS: /var/www/html/media/keograms
            ALLSKY_STARTRAILS: /var/www/html/media/startrails

    webdav:
        image: k3vmcd/webdav
        ports:
            - 443:443/tcp
        volumes:
            - type: volume
              source: media
              target: /var/lib/dav/allsky
        secrets:
            - source: htpasswd
              target: /user.passwd
        environment:
            ANONYMOUS_METHODS: GET
            AUTH_TYPE: Basic
            SSL_CERT: selfsigned
            SERVER_NAMES: allsky.cloud.cherryservers.net

volumes:
    media:

configs:
    config.js:
        external: true

secrets:
    htpasswd:
        external: true
