version: '3.7'

services:

    app:
        image: ghcr.io/minjja/allsky-website
        ports:
            - 80:80/tcp
        configs:
            - source: config.js
              target: /var/www/html/config.js
        volumes:
            - type: volume
              source: videos
              target: /var/www/html/videos
            - type: volume
              source: keograms
              target: /var/www/html/keograms
            - type: volume
              source: startrails
              target: /var/www/html/startrails
        depends_on:
            - webdav

    webdav:
        image: k3vmcd/webdav
        ports:
            - 8080:80
        volumes:
            - type: volume
              source: videos
              target: /var/lib/dav/videos
            - type: volume
              source: keograms
              target: /var/lib/dav/keograms
            - type: volume
              source: startrails
              target: /var/lib/dav/startrails
        secrets:
            - source: htpasswd
              target: /user.passwd

volumes:
    videos:
    keograms:
    startrails:

configs:
    config.js:
        external: true
    htpasswd:
        external: true
