version: '3.8'

services:

    httpd:
        image: httpd
        volumes:
          - ./public/:/usr/local/apache2/htdocs/
        ports:
            - 80:80/tcp

    certbot:
        image: certbot/certbot
        volumes:
            - ./etc/letsencrypt/:/etc/letsencrypt/
            - ./public/:/public/
        command: |
            certonly
            --webroot --webroot-path=/public
            --register-unsafely-without-email 
            --agree-tos
            -d allsky.cloud.cherryservers.net
            -v
        depends_on:
            - httpd
