version: '3.7'

services:

    nginx:
        image: nginx
        ports:
            - 80:80/tcp
            - 443:443/tcp
        configs:
            - source: nginx.conf
              target: /etc/nginx/conf.d/default.conf
        secrets:
            - source: ssl_certificate
              target: /etc/letsencrypt/cert.crt
            - source: ssl_certificate_key
              target: /etc/letsencrypt/private.key

    webdav:
        image: ghcr.io/minjja/webdav
        secrets:
            - source: htpasswd
              target: /etc/apache2/.htpasswd
        configs:
            - source: webdav.alias.conf
              target: /etc/apache2/conf-enabled/002-webdav.alias.conf
            - source: webdav.anonymous.read.conf
              target: /etc/apache2/conf-enabled/001-webdav.anonymous.read.conf
        volumes:
            - type: volume
              source: webdav
              target: /var/www/html

    website:
        image: ghcr.io/minjja/allsky-website
        configs:
            - source: php.ini
              target: /usr/local/etc/php/php.ini
            - source: config.js
              target: /var/www/html/config.js
            - source: virtualsky.json
              target: /var/www/html/virtualsky.json
        environment:
            ALLSKY_VIDEOS: ../../webdav/videos
            ALLSKY_KEOGRAMS: ../../webdav/keograms
            ALLSKY_STARTRAILS: ../../webdav/startrails

volumes:
    webdav:

configs:
    php.ini:
        file: ./etc/php.ini
    nginx.conf:
        file: ./etc/nginx.conf
    config.js:
        file: ./src/config.js
    virtualsky.json:
        file: ./src/virtualsky.json
    webdav.alias.conf:
        file: ./etc/webdav.alias.conf
    webdav.anonymous.read.conf:
        file: ./etc/webdav.anonymous.read.conf

secrets:
    htpasswd:
        external: true
    ssl_certificate:
        file: ./etc/letsencrypt/live/allsky/cert.pem
    ssl_certificate_key:
        file: ./etc/letsencrypt/live/allsky/privkey.pem
